[[redirects]]
  from = "/api/*"
  to = "https://vaultwarden.oyanglul.us/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
[[redirects]]
  from = "/identity/*"
  to = "https://vaultwarden.oyanglul.us/identity/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
[[redirects]]
  from = "/icons/*"
  to = "https://vaultwarden.oyanglul.us/icons/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
[[redirects]]
  from = "/attachments/*"
  to = "https://vaultwarden.oyanglul.us/attachments/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
